[build]
  publish="dist"
  command="yarn prod"

[[redirects]]
  from = "https://stimulus-checkbox-tree.netlify.app/*"
  to = "https://stimulus-checkbox-tree.berry.sh/:splat"
  status = 301
  force = true
